version: "2"

services: 
    ganache:
        image: trufflesuite/ganache-cli:latest
        command: ganache-cli -h 0.0.0.0
        ports: 
            - 8545:8545

    ipfs:
        container_name: ipfs
        build: 
            context: ./custom-ipfs
            dockerfile: Dockerfile
        ports: 
            - 4001:4001
            - 5001:5001
            - 8080:8080
            - 8081:8081

    photoblock:
        container_name: photoblock
        build: 
            context: ./
            dockerfile: Dockerfile
        command: >
            sh -c "truffle compile &&
                    truffle test &&
                    truffle migrate --reset &&
                    cd client &&
                    npm run start"
        ports: 
            - "3000:3000"
        depends_on: 
            - ganache
            - ipfs
        tty: true
        volumes: 
            - './client/src:/app/client/src'
            - './client/node_modules:/app/client/node_modules'